<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
       public function liste() {
        return $this->getEntityManager()
                       ->createQueryBuilder()
                        ->select('u')
                        ->from('appBundle:User','u')
                        ->leftJoin('a.amis', 'a')
                        ->getResult(Query::HYDRATE_ARRAY);
    }       
